name: Call Reusable Workflow

on:
  push:
    branches:
      - develop
      - main

jobs:
  call:
    uses: ./.github/workflows/docker-ci.yml@v1.0.0

    with:
      image_name: myapp
      tag: ${{ github.ref == 'refs/heads/main' && format('prod-{0}', github.sha) || format('staging-{0}', github.sha) }}

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
