name: Task4 PR Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build step"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Test step"
