name: Task3 Context

on:
  push:
    branches:
      - main

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
